package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonBackReference;

@DynamoDBTable(tableName = "Drive")
public class Drive {

	private Integer id;
	private Vehicle vehicle;
	private List<OBDReading> obdreadings = new ArrayList<OBDReading>();	
	
	/*Generic constructor*/
	public Drive() {
    }
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
    @DynamoDBAttribute
	public List<OBDReading> getObdreadings() {
		return obdreadings;
	}

	public void setObdreadings(List<OBDReading> obdreadings) {
		this.obdreadings = obdreadings;
	}

    @DynamoDBAttribute
	public Vehicle getVehicle() {
		return vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}
}
