package com.example.demo.authentication;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "User")
public class User {

	private int id;
	private String email;
	private String password;
	private String name;
	private String lastName;
	private int active;
	private Set<Role> roles;
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
    
    @DynamoDBAttribute
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
    @DynamoDBAttribute
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
    @DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
    @DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
    @DynamoDBAttribute
	public int getActive() {
		return active;
	}

	public void setActive(int active) {
		this.active = active;
	}
	@DynamoDBAttribute
	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
